# docker-compose.yml
# Запуск: docker compose up --build
# или из папки frontend: npm run docker:prod

services:
  # Бэкенд сервис
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile # Используем Dockerfile для продакшена
    environment:
      - SPRING_PROFILES_ACTIVE=prod
    ports:
      - '8080:8080' # Основной порт приложения
    networks:
      - cardtopia-net

  # Фронтенд сервис
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile # Используем Dockerfile для продакшена
    ports:
      - '3000:3000' # Порт для Next.js
    environment:
      - NEXT_PUBLIC_API_URL_SERVER=http://backend:8080 # URL для запросов на бэкенд со стороны сервера (внутри Docker)
      - NEXT_PUBLIC_API_URL=http://localhost:8080 # URL для запросов на бэкенд со стороны клиента (в браузере)
    networks:
      - cardtopia-net

# Сеть для взаимодействия контейнеров
networks:
  cardtopia-net:
    driver: bridge
